# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cff34afbdc79f22f7aa5c3d6f03e18f1081e82480513b78c613ea868012fa1c3c0df857830e1e0316050085b9dd6e1fc70cb54dca9e045e0be3b97975acc220f

test:
  secret_key_base: 9b394f1f24ea6707733915a9595664fa027132aa7d12708d560caaa51fd84646f8815fada32b5eae8a3ea38bf3cd3f1f04e5d91d4b18c573347d2033c2c9183a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
